name: "Validate Issues over Pull Requests"
description: "Checks for a valid Issue number linked with the PR"
author: "Harsh Mishra"
branding:
  icon: 'activity'
  color: 'white'

inputs:
  prbody:
    description: "Body of the Pull Request to search for related issues"
    required: true
    
  prurl:
    description: "URL of the Pull Request"
    required: true
    
outputs:
  valid:
    description: "code for a valid issue (0=Invalid, 1=Valid)"
    
runs:
  using: "docker"
  image: "Dockerfile"
